# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  reconnect: false
  socket: <%= [
                "/run/mysqld/mysqld5.6.sock",
                "/tmp/mysql.sock",
                "/tmp/mysqld.sock",
                "/var/run/mysqld/mysqld.sock",
                "/var/lib/mysql/mysql.sock",
                "/opt/local/var/run/mysql5/mysqld.sock",
               ].detect {|s| File.exist?(s) } %>

development:
  <<: *default
  database: app_development
  database: <%= ENV['DB_NAME'].presence || 'app_development' %>
  username: <%= ENV['DB_USER_NAME'].presence || 'root' %>
  password: <%= ENV['DB_PASS'].presence || '' %>
  host: <%= ENV['DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['DB_PORT'].presence || 3306 %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: app_test
  database: <%= ENV['DB_NAME'].presence || 'app_development' %>
  username: <%= ENV['DB_USER_NAME'].presence || 'root' %>
  password: <%= ENV['DB_PASS'].presence || '' %>
  host: <%= ENV['DB_HOST'].presence || 'localhost' %>
  port: <%= ENV['DB_PORT'].presence || 3306 %>

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: app_production
  username: app_user
  password: <%= ENV['RAILS-ON-DOCKER_DATABASE_PASSWORD'] %>
